SEPARATOR := ===================================================================

.PHONY: run%
run%:
	+cd day$* && \
	echo $(SEPARATOR) && echo && \
	$(MAKE) --quiet run && \
	echo && echo $(SEPARATOR)
